import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { House, Sparkles, Search, Heart, MapPin, SlidersHorizontal, X, BedDouble, Bath, Maximize, Check, ChevronDown, Menu, LayoutGrid, Map as MapIcon, Bookmark, CarFront, PawPrint, WashingMachine, ArrowUp, Plus, Minus, UserRound, Bell, ShieldCheck, Info, LogOut, RotateCcw, LoaderCircle, CheckCheck, ChevronRight, Building2 } from 'lucide-react';
import { cities, demoListings, money } from './data';
import { defaultFilters, interpretQuery, getMatches, matchReasons } from './search';
import './styles.css';

const uuid = () => crypto.randomUUID?.() ?? '10000000-1000-4000-8000-100000000000'.replace(/[018]/g, c => (Number(c) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> Number(c) / 4).toString(16));
const readLocal = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const writeLocal = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} };
function Brand() { return <span className="brand"><span className="brand-icon"><House size={24}/><Sparkles size={13} className="brand-spark"/></span><span>forrent<span className="brand-suffix">.si</span></span></span>; }
function Modal({ title, children, close, wide = false }) {
  const ref = useRef(null);
  useEffect(() => { const d = ref.current; d.showModal(); return () => d.close(); }, []);
  return <dialog ref={ref} onCancel={close} onClick={e => { if(e.target === ref.current) close(); }} className={wide ? 'modal wide' : 'modal'}><div className="modal-heading"><h2>{title}</h2><button className="icon-btn" onClick={close} aria-label="Close dialog"><X/></button></div>{children}</dialog>;
}
function RentalMap({ listings, city, onSelect }) {
  const container = useRef(null), mapRef = useRef(null), layerRef = useRef(null), leaflet = useRef(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    let cancelled = false;
    Promise.all([import('leaflet'), import('leaflet/dist/leaflet.css')]).then(([mod]) => {
      if (cancelled || !container.current) return;
      const L = mod.default; leaflet.current = L;
      const map = L.map(container.current, { zoomControl: true, scrollWheelZoom: false }).setView(cities[city]?.center || [39.5,-98.35], 13);
      mapRef.current = map;
      L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>', maxZoom: 18 }).on('tileerror',()=>setFailed(true)).addTo(map);
      layerRef.current = L.layerGroup().addTo(map);
      updateMarkers();
      setTimeout(() => { if (!cancelled) map.invalidateSize(); }, 150);
    }).catch(() => setFailed(true));
    function updateMarkers() {
      if(!leaflet.current || !layerRef.current) return;
      const L = leaflet.current;
      layerRef.current.clearLayers();
      listings.forEach(p => L.marker([p.lat,p.lng], { icon: L.divIcon({ className:'price-pin',html:`<span>${money(p.rent)}</span>`,iconSize:[80,36],iconAnchor:[40,18] }) }).addTo(layerRef.current).on('click',()=>onSelect(p)));
    }
    return () => { cancelled = true; mapRef.current?.remove(); mapRef.current=null; };
  }, []);
  useEffect(() => {
    if(!mapRef.current || !leaflet.current) return;
    mapRef.current.setView(cities[city]?.center || [39.5,-98.35],13);
    const L=leaflet.current; layerRef.current.clearLayers();
    listings.forEach(p=>L.marker([p.lat,p.lng],{icon:L.divIcon({className:'price-pin',html:`<span>${money(p.rent)}</span>`,iconSize:[80,36],iconAnchor:[40,18]})}).addTo(layerRef.current).on('click',()=>onSelect(p)));
  }, [listings,city,onSelect]);
  return <div className="map-panel"><div ref={container} className="rental-map" aria-label={`Map of ${city} sample apartments`}/><span className="map-note"><Info size={14}/> {listings.some(p=>p.is_demo)?'Sample locations · not real listings':'Listing locations'}</span>{failed && <p className="map-error">Map tiles couldn't load. You can still select prices or browse the list.</p>}</div>;
}
function ListingCard({ p, saved, toggleSave, select, filters, compare, toggleCompare }) {
  return <article className="listing-card">
    <div className="card-image-wrap"><button className="image-button" onClick={()=>select(p)} aria-label={`View ${p.name}`}><img src={p.image} alt={`Illustrative apartment interior for ${p.name}`} loading="lazy"/></button>{p.is_demo&&<span className="photo-label">Sample home</span>}<button className={`save-heart ${saved?'saved':''}`} onClick={()=>toggleSave(p.id)} aria-label={`${saved?'Unsave':'Save'} ${p.name}`} aria-pressed={saved}><Heart size={19} fill={saved?'currentColor':'none'}/></button><span className="photo-count">1 / 1</span></div>
    <div className="card-body"><div className="price-row"><p className="price">{money(p.rent)}<span> / mo</span></p><span className="match-pill"><CheckCheck size={13}/>{filters.maxRent||filters.beds!=='any'||filters.pets||filters.parking||filters.laundry?'Fits your filters':'Explore this home'}</span></div><button className="card-title" onClick={()=>select(p)}>{p.name}</button><p className="location"><MapPin size={13}/>{p.area} · {p.city}, {p.state}</p><div className="specs"><span><BedDouble/>{p.beds===0?'Studio':`${p.beds} bed${p.beds>1?'s':''}`}</span><span><Bath/>{p.baths} bath{p.baths>1?'s':''}</span><span><Maximize/>{p.sqft.toLocaleString()} sqft</span></div><div className="card-tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><div className="card-bottom"><span>{money(p.rent+p.fees)} incl. listed fees</span><label><input type="checkbox" checked={compare.includes(p.id)} onChange={()=>toggleCompare(p.id)}/>Compare</label></div></div>
  </article>;
}
function App() {
  const [page,setPage]=useState('discover'),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[filters,setFilters]=useState(defaultFilters),[filterOpen,setFilterOpen]=useState(false),[view,setView]=useState('grid'),[sort,setSort]=useState('recommended');
  const [saved,setSaved]=useState(()=>readLocal('forrent.saved',[])),[savedSearches,setSavedSearches]=useState(()=>readLocal('forrent.searches',[])),[profile,setProfile]=useState(()=>readLocal('forrent.profile',{name:'',city:'Bozeman',budget:'2200',pets:false,laundry:false,parking:false}));
  const [selected,setSelected]=useState(null),[dialog,setDialog]=useState(null),[toast,setToast]=useState(''),[compare,setCompare]=useState([]),[config,setConfig]=useState({demo:true}),[supabase,setSupabase]=useState(null),[user,setUser]=useState(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[listings,setListings]=useState(demoListings),[searchRun,setSearchRun]=useState(false),[authMode,setAuthMode]=useState('signup'),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false),[cloudReady,setCloudReady]=useState(false);
  const toastTimer=useRef(null);
  const notify=msg=>{setToast(msg);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);};
  useEffect(()=>{let active=true;fetch('/api/config').then(r=>r.ok?r.json():Promise.reject()).then(c=>{if(!active)return;setConfig(c);if(c.supabaseUrl&&c.supabaseKey)setSupabase(createClient(c.supabaseUrl,c.supabaseKey));}).catch(()=>{});return()=>{active=false;};},[]);
  useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data}=supabase.auth.onAuthStateChange((event,session)=>{setUser(session?.user??null);if(event==='PASSWORD_RECOVERY')setDialog('reset');});return()=>data.subscription.unsubscribe();},[supabase]);
  useEffect(()=>{writeLocal('forrent.saved',saved);},[saved]);
  useEffect(()=>{writeLocal('forrent.searches',savedSearches);},[savedSearches]);
  useEffect(()=>{writeLocal('forrent.profile',profile);},[profile]);
  useEffect(()=>{
    if(!supabase||config.demo)return;
    let active=true;setLoading(true);
    supabase.from('listings').select('*').eq('status','active').eq('city',filters.city).limit(200).then(({data,error})=>{if(!active)return;if(error){setListings([]);setNotice('Listings could not load. Please try again.');}else setListings((data??[]).map(p=>({...p,image:p.image_url||'/images/apartment-1.jpg',fees:p.monthly_fees,tags:p.amenities,is_demo:false})));setLoading(false);});
    return()=>{active=false;};
  },[supabase,config.demo,filters.city]);
  useEffect(()=>{
    setCloudReady(false);if(!supabase||!user)return;
    let active=true;Promise.all([supabase.from('renter_profiles').select('*').eq('user_id',user.id).maybeSingle(),supabase.from('saved_homes').select('listing_key').eq('user_id',user.id),supabase.from('saved_searches').select('*').eq('user_id',user.id)]).then(([pr,sv,ss])=>{if(!active)return;if(pr.error||sv.error||ss.error){notify('Account storage is not ready. Your changes remain on this device.');return;}setSaved((sv.data??[]).map(r=>r.listing_key));setSavedSearches((ss.data??[]).map(r=>({id:r.id,query:r.query,filters:r.filters})));if(pr.data)setProfile(p=>({...p,...pr.data.preferences}));setCloudReady(true);});return()=>{active=false;};
  },[supabase,user?.id]);
  const changeFilter=(name,value)=>{setFilters(f=>({...f,[name]:value}));setSearchRun(true);};
  const toggleSave=async id=>{const exists=saved.includes(id);if(user&&supabase&&cloudReady){const {error}=exists?await supabase.from('saved_homes').delete().eq('user_id',user.id).eq('listing_key',id):await supabase.from('saved_homes').insert({user_id:user.id,listing_key:id});if(error){notify('Could not save this home. Please try again.');return;}}setSaved(s=>exists?s.filter(v=>v!==id):[...s,id]);notify(exists?'Home removed from favorites':user&&cloudReady?'Home saved to your account':'Home saved on this device');};
  const saveSearch=async()=>{const id=uuid(),item={id,query:query.trim()||`${filters.city} apartment search`,filters:{...filters}};if(user&&supabase&&cloudReady){const {error}=await supabase.from('saved_searches').insert({...item,user_id:user.id});if(error){notify('Could not save this search. Please try again.');return;}}setSavedSearches(s=>[item,...s]);notify('Search saved. Email alerts will be available with live listings.');};
  const removeSearch=async id=>{if(user&&supabase&&cloudReady){const {error}=await supabase.from('saved_searches').delete().eq('id',id).eq('user_id',user.id);if(error){notify('Could not remove search.');return;}}setSavedSearches(s=>s.filter(x=>x.id!==id));};
  const runSearch=async(e,text=query)=>{e?.preventDefault();setLoading(true);setPage('discover');setSearchRun(true);setNotice('');let next=interpretQuery(text,filters.city);if(config.ai&&user){try{const {data}=await supabase.auth.getSession();const response=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({query:text,city:filters.city})});if(!response.ok)throw new Error();const parsed=await response.json();next=parsed.filters;setNotice(parsed.note||'');}catch{setNotice('AI interpretation is temporarily unavailable. Basic filters were applied; review them below.');}}else setNotice('Search preview understands city, budget, bedrooms, pets, parking, and laundry. Other preferences still need confirmation.');setFilters(next);setLoading(false);};
  const toggleCompare=id=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<3?[...c,id]:(notify('Choose up to 3 homes to compare.'),c));
  const reset=()=>{setFilters(defaultFilters);setQuery('');setSearchRun(false);setNotice('');};
  const filtered=useMemo(()=>{let r=page==='saved'?listings.filter(p=>saved.includes(p.id)):getMatches(listings,filters);if(sort==='price-low')r.sort((a,b)=>(a.rent+a.fees)-(b.rent+b.fees));if(sort==='price-high')r.sort((a,b)=>(b.rent+b.fees)-(a.rent+a.fees));if(sort==='space')r.sort((a,b)=>b.sqft-a.sqft);return r;},[listings,filters,page,saved,sort]);
  const activeFilters=[filters.maxRent&&`Under ${money(Number(filters.maxRent))} total`,filters.beds!=='any'&&(filters.beds==='0'?'Studio':`${filters.beds} bedrooms`),filters.pets&&'Pet friendly',filters.parking&&'Parking',filters.laundry&&'In-unit laundry'].filter(Boolean);
  const navigate=p=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'search_rental_homes',description:'Apply a rental search to the visible sample or live inventory. Does not contact landlords.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:1500}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.query!=='string'||input.query.length>1500)throw new Error('A query of up to 1500 characters is required');const f=interpretQuery(input.query,filters.city);setQuery(input.query);setFilters(f);setPage('discover');setSearchRun(true);return{mode:config.demo?'sample':'live',filters:f,count:getMatches(listings,f).length};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[filters.city,listings,config.demo]);
  const submitAuth=async e=>{e.preventDefault();if(!supabase)return;setAuthBusy(true);setAuthError('');const form=new FormData(e.currentTarget);const email=String(form.get('email')||''),password=String(form.get('password')||'');let result;if(dialog==='reset')result=await supabase.auth.updateUser({password});else if(authMode==='forgot')result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});else if(authMode==='signup')result=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});else result=await supabase.auth.signInWithPassword({email,password});setAuthBusy(false);if(result.error){setAuthError(result.error.message);return;}if(authMode==='forgot'){setAuthError('If an account exists, a reset email is on its way.');return;}if(authMode==='signup'&&!result.data.session){setAuthError('Check your email to confirm your account, then log in.');return;}setDialog(null);notify(dialog==='reset'?'Password updated':'You’re logged in');};
  return <>
    <header className="header"><div className="header-inner"><button className="brand-button" onClick={()=>navigate('discover')} aria-label="forrent.si home"><Brand/></button><nav className={menu?'nav open':'nav'} aria-label="Main navigation"><button className={page==='discover'?'active':''} onClick={()=>navigate('discover')}>Discover</button><button className={page==='saved'?'active':''} onClick={()=>navigate('saved')}>Saved homes {saved.length>0&&<span className="nav-count">{saved.length}</span>}</button><button className={page==='searches'?'active':''} onClick={()=>navigate('searches')}>My searches</button></nav><div className="header-actions">{user?<button className="profile-button" onClick={()=>navigate('profile')}><UserRound size={17}/><span>My profile</span></button>:<><button className="login-button" onClick={()=>{setAuthMode('login');setAuthError('');setDialog('auth');}}>Log in</button><button className="primary small" onClick={()=>{setAuthMode('signup');setAuthError('');setDialog('auth');}}>Sign up</button></>}<button className="mobile-menu icon-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></div></header>
    <main>
      {page==='discover'&&<>
        <section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> A MORE PERSONAL WAY TO RENT</div><h1>A place that feels<br/>{' '}like <span>you.</span></h1><p>Tell us what matters. Find a home that fits your life.</p></div><div className="search-area"><form className="natural-search" onSubmit={runSearch}><label htmlFor="home-search"><Sparkles size={19}/> What does your next home look like?</label><textarea id="home-search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={1500} rows={2} placeholder="A sunny 2-bedroom in Bozeman, under $2,200, with room for my dog…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();runSearch(e);}}}/><div className="search-footer"><span>{config.ai&&user?'AI-powered search':'Smart search preview'}</span><button className="primary" disabled={loading}>{loading?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>}Find my place</button></div></form><div className="suggestions"><span>Try a little inspiration</span>{['Pet-friendly under $2,000','2 beds with parking','Studio in Denver'].map((s,i)=><button key={s} onClick={()=>{setQuery(s);runSearch(null,s);}}>{i===0?<PawPrint size={13}/>:i===1?<CarFront size={13}/>:<Building2 size={13}/>} {s}</button>)}</div></div></section>
        <section className="search-workspace"><div className="filter-bar"><label className="city-picker"><MapPin size={18}/><select value={filters.city} onChange={e=>changeFilter('city',e.target.value)} aria-label="Search city">{Object.keys(cities).map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></label><div className="filter-divider"/><label className="filter-select"><select value={filters.maxRent} onChange={e=>changeFilter('maxRent',e.target.value)} aria-label="Maximum monthly cost"><option value="">Any price</option>{[1500,1800,2000,2200,2500,3000,3500].map(n=><option value={n} key={n}>Under {money(n)}</option>)}{filters.maxRent&&![1500,1800,2000,2200,2500,3000,3500].includes(Number(filters.maxRent))&&<option value={filters.maxRent}>Under {money(Number(filters.maxRent))}</option>}</select><ChevronDown size={14}/></label><label className="filter-select"><select value={filters.beds} onChange={e=>changeFilter('beds',e.target.value)} aria-label="Bedrooms"><option value="any">Bedrooms</option><option value="0">Studio</option><option value="1">1 bedroom</option><option value="2">2 bedrooms</option><option value="3+">3+ bedrooms</option>{filters.beds==='3'&&<option value="3">3 bedrooms</option>}{filters.beds==='4'&&<option value="4">4 bedrooms</option>}</select><ChevronDown size={14}/></label><button className={`filter-chip ${filters.pets?'selected':''}`} onClick={()=>changeFilter('pets',!filters.pets)} aria-pressed={filters.pets}><PawPrint size={16}/>Pet friendly</button><button className="filter-chip more-filters" onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/>More filters{(filters.parking||filters.laundry)&&<span className="filter-dot"/>}</button><button className="save-search" onClick={saveSearch}><Bookmark size={17}/>Save search</button></div></section>
      </>}
      {(page==='discover'||page==='saved')&&<section className="results-section">
        {config.demo&&<div className="demo-strip"><span className="demo-badge">EARLY PREVIEW</span><p>Explore sample homes. Live listings are on the way.</p><button onClick={()=>setDialog('about')}>About this preview <Info size={14}/></button></div>}
        <div className="results-heading"><div><p className="overline">{page==='saved'?'YOUR SHORTLIST':searchRun?'YOUR SEARCH RESULTS':'FIND YOUR EVERYDAY'}</p><h2>{page==='saved'?'Places you’re thinking about':`Make yourself at home in ${filters.city}`}</h2><p>{loading?'Finding your places…':`${filtered.length} ${config.demo?'sample ':''}homes${page==='saved'?' saved':` to explore`}`}<span className="text-dot">·</span>{page==='saved'?(user&&cloudReady?'Synced to your account':'Saved on this device'):cities[filters.city]?.subtitle}</p></div><div className="result-controls"><label className="sort"><span>Sort:</span><select aria-label="Sort homes" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="price-low">Lowest total cost</option><option value="price-high">Highest total cost</option><option value="space">Most space</option></select><ChevronDown size={14}/></label><div className="view-switch"><button aria-label="Grid view" aria-pressed={view==='grid'} className={view==='grid'?'on':''} onClick={()=>setView('grid')}><LayoutGrid size={16}/><span>Grid</span></button><button aria-label="Map view" aria-pressed={view==='map'} className={view==='map'?'on':''} onClick={()=>setView('map')}><MapIcon size={16}/><span>Map</span></button></div></div></div>
        {page==='discover'&&activeFilters.length>0&&<div className="active-filters">{activeFilters.map(f=><span key={f}><Check size={13}/>{f}</span>)}<button onClick={reset}>Clear all</button></div>}
        {notice&&page==='discover'&&<div className="search-notice"><Sparkles size={16}/><p>{notice}</p><button onClick={()=>setNotice('')} className="icon-btn" aria-label="Dismiss search note"><X size={15}/></button></div>}
        {filtered.length===0&&!loading?<div className="empty-state"><Search size={34}/><h3>{page==='saved'?'Your next favorite is out there.':'No homes match all of those details.'}</h3><p>{page==='saved'?'Tap a heart on any home to keep it here.':'Try a higher budget or fewer must-haves. We won’t quietly change your search.'}</p><button className="primary" onClick={()=>{reset();navigate('discover');}}>Explore homes</button></div>:<div className={view==='map'?'results-layout with-map':'results-layout'}><div className="listing-grid">{filtered.map(p=><ListingCard key={p.id} p={p} saved={saved.includes(p.id)} toggleSave={toggleSave} select={setSelected} filters={filters} compare={compare} toggleCompare={toggleCompare}/>)}</div>{view==='map'&&<RentalMap listings={filtered} city={filters.city} onSelect={setSelected}/>}</div>}
        {page==='discover'&&<div className="bottom-callout"><div className="callout-icon"><Sparkles size={25}/></div><div><h3>Your must-haves. Your kind of home.</h3><p>Save your preferences to make the next search feel a little more like you.</p></div><button className="secondary" onClick={()=>navigate('profile')}>Set my preferences</button></div>}
      </section>}
      {page==='searches'&&<section className="account-page"><p className="overline">PICK UP WHERE YOU LEFT OFF</p><h1>Your saved searches</h1><p className="muted">{user&&cloudReady?'Saved to your account.':'Saved on this device.'} Email alerts will be available once live listings are connected.</p>{!savedSearches.length?<div className="empty-state"><Bookmark size={36}/><h3>A good search is worth keeping.</h3><p>Set your filters, then choose Save search.</p><button className="primary" onClick={()=>navigate('discover')}>Find my place</button></div>:<div className="search-list">{savedSearches.map(s=><article key={s.id}><div className="search-list-icon"><Search size={21}/></div><div><h3>{s.query}</h3><p>{s.filters.city} · {s.filters.maxRent?`Under ${money(Number(s.filters.maxRent))}`:'Any budget'} · {s.filters.beds==='any'?'Any bedrooms':s.filters.beds==='0'?'Studio':`${s.filters.beds} bedrooms`}</p></div><button className="secondary" onClick={()=>{setFilters(s.filters);setQuery(s.query);setSearchRun(true);navigate('discover');}}>Run search</button><button className="icon-btn" aria-label={`Delete search ${s.query}`} onClick={()=>removeSearch(s.id)}><X size={19}/></button></article>)}</div>}</section>}
      {page==='profile'&&<section className="account-page"><p className="overline">MAKE ROOM FOR WHAT MATTERS</p><h1>Your home preferences</h1><p className="muted">A starting point for your next search. {user&&cloudReady?'Synced to your account.':'Kept on this device.'}</p><form className="profile-form" onSubmit={async e=>{e.preventDefault();if(supabase&&user&&cloudReady){const {error}=await supabase.from('renter_profiles').upsert({user_id:user.id,preferences:profile});if(error){notify('Could not sync preferences. Please try again.');return;}}setFilters({...defaultFilters,city:profile.city,maxRent:profile.budget,pets:profile.pets,parking:profile.parking,laundry:profile.laundry});setSearchRun(true);navigate('discover');notify('Your preferences are ready.');}}><label>Your first name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} maxLength={60} placeholder="What should we call you?"/></label><div className="form-row"><label>Where are you looking?<select value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})}>{Object.keys(cities).map(c=><option key={c}>{c}</option>)}</select></label><label>Monthly budget, including listed fees<input type="number" min="100" max="50000" step="50" value={profile.budget} onChange={e=>setProfile({...profile,budget:e.target.value})} required/></label></div><h3>What makes it home?</h3><div className="preference-options">{[['pets','Pet friendly',PawPrint],['parking','Parking',CarFront],['laundry','In-unit laundry',WashingMachine]].map(([key,label,Icon])=><label key={key} className={profile[key]?'chosen':''}><Icon size={20}/>{label}<input type="checkbox" checked={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.checked})}/></label>)}</div><button className="primary">Save & find homes</button></form>{user&&<button className="text-button" onClick={async()=>{await supabase.auth.signOut();setSaved([]);setSavedSearches([]);setProfile({name:'',city:'Bozeman',budget:'2200',pets:false,parking:false,laundry:false});navigate('discover');notify('Logged out');}}><LogOut size={16}/>Log out</button>}</section>}
    </main>
    <footer><Brand/><p>A more personal way to find home.</p><div><button onClick={()=>setDialog('about')}>About</button><button onClick={()=>setDialog('privacy')}>Privacy</button><span>© {new Date().getFullYear()} forrent.si</span></div></footer>
    {compare.length>0&&<div className="compare-bar"><span><CheckCheck size={19}/>{compare.length} home{compare.length>1?'s':''} selected</span><button className="primary small" onClick={()=>setDialog('compare')}>Compare homes</button><button className="icon-btn" onClick={()=>setCompare([])} aria-label="Clear comparison"><X size={18}/></button></div>}
    {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {filterOpen&&<Modal title="Make it your kind of place" close={()=>setFilterOpen(false)}><p className="muted">All selected preferences must match.</p><div className="modal-filters">{[['pets','Pet friendly',PawPrint],['parking','Parking available',CarFront],['laundry','In-unit laundry',WashingMachine]].map(([key,label,Icon])=><label key={key}><Icon size={21}/><span>{label}</span><input type="checkbox" checked={filters[key]} onChange={e=>changeFilter(key,e.target.checked)}/></label>)}</div><p className="small-note">Pet restrictions, parking costs, and availability still need confirmation.</p><div className="modal-actions"><button className="text-button" onClick={()=>setFilters(defaultFilters)}>Reset filters</button><button className="primary" onClick={()=>setFilterOpen(false)}>Show {getMatches(listings,filters).length} homes</button></div></Modal>}
    {selected&&<Modal title={selected.name} close={()=>setSelected(null)} wide><div className="detail-photo"><img src={selected.image} alt={`Illustrative interior for ${selected.name}`}/>{selected.is_demo&&<span className="photo-label">Sample home · illustrative photo</span>}</div><div className="detail-layout"><div><p className="location"><MapPin size={15}/>{selected.area} · {selected.city}, {selected.state}</p><div className="detail-specs"><span><BedDouble/>{selected.beds===0?'Studio':`${selected.beds} bedroom${selected.beds>1?'s':''}`}</span><span><Bath/>{selected.baths} bathrooms</span><span><Maximize/>{selected.sqft.toLocaleString()} sqft</span></div><p className="description">{selected.description}</p><div className="why-match"><h3><Sparkles size={19}/>Why it could feel like home</h3>{matchReasons(selected,filters).map(r=><p key={r}><Check size={15}/>{r}</p>)}</div><h3>The everyday essentials</h3><div className="amenities">{selected.tags.map(t=><span key={t}><Check size={15}/>{t}</span>)}</div>{selected.is_demo&&<p className="detail-disclaimer">This is a fictional sample home. Photos, pricing, amenities, and map locations illustrate the experience. It cannot be rented or toured.</p>}</div><aside className="cost-card"><p className="price">{money(selected.rent)}<span> / month</span></p><p className="muted">Let’s look at the whole picture.</p><dl><div><dt>Base rent</dt><dd>{money(selected.rent)}</dd></div><div><dt>Listed monthly fees</dt><dd>{money(selected.fees)}</dd></div><div className="total"><dt>Listed monthly total</dt><dd>{money(selected.rent+selected.fees)}</dd></div></dl><p className="small-note">Utilities, pet costs, and other unlisted charges may be additional.</p><div className="deposit"><span>{selected.is_demo?'Illustrative security deposit':'Listed security deposit'}</span><strong>{selected.deposit==null?'Not provided':money(selected.deposit)}</strong></div><button className="primary" onClick={()=>toggleSave(selected.id)}><Heart size={17} fill={saved.includes(selected.id)?'currentColor':'none'}/>{saved.includes(selected.id)?'Saved to favorites':'Save this home'}</button>{selected.is_demo?<p className="small-note centered">Tour requests open with live listings.</p>:selected.source_url&&/^https:\/\//.test(selected.source_url)&&<a className="secondary source-link" href={selected.source_url} target="_blank" rel="noreferrer">View original listing</a>}</aside></div></Modal>}
    {(dialog==='auth'||dialog==='reset')&&<Modal title={dialog==='reset'?'Choose a new password':authMode==='signup'?'Make yourself at home':authMode==='forgot'?'Reset your password':'Welcome home'} close={()=>setDialog(null)}>{!supabase?<div className="auth-preview"><span className="auth-house"><House size={30}/></span><h3>Accounts are coming next.</h3><p>You can already explore homes, save favorites, and keep your preferences on this device. Account syncing will open when our secure sign-in is connected.</p><button className="primary" onClick={()=>{setDialog(null);navigate('profile');}}>Set my preferences</button></div>:<form className="auth-form" onSubmit={submitAuth}><p className="muted">{authMode==='signup'?'Keep your favorite homes and searches together.':'Your next chapter is waiting.'}</p>{dialog!=='reset'&&<label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@example.com"/></label>}{(dialog==='reset'||authMode!=='forgot')&&<label>Password<input name="password" type="password" required minLength={8} autoComplete={authMode==='signup'?'new-password':'current-password'}/></label>}{authError&&<p className="auth-message" role="status">{authError}</p>}<button className="primary" disabled={authBusy}>{authBusy?'Please wait…':dialog==='reset'?'Update password':authMode==='signup'?'Create account':authMode==='forgot'?'Send reset link':'Log in'}</button>{dialog!=='reset'&&<div className="auth-links"><button type="button" onClick={()=>{setAuthMode(authMode==='signup'?'login':'signup');setAuthError('');}}>{authMode==='signup'?'Already have an account? Log in':'New here? Create an account'}</button>{authMode==='login'&&<button type="button" onClick={()=>{setAuthMode('forgot');setAuthError('');}}>Forgot password?</button>}</div>}</form>}</Modal>}
    {dialog==='about'&&<Modal title="A better way to find your place" close={()=>setDialog(null)}><div className="prose"><p>forrent.si is being built around one idea: finding a home should start with your life, your budget, and what matters to you.</p><h3>You’re exploring an early preview.</h3><p>The homes in this collection are fictional. Photos are illustrative, and prices, fees, amenities, and locations are sample data. No bookings, applications, or payments are accepted.</p><p>Search, filters, comparisons, saved homes, and preferences are available to try. Licensed listing feeds and secure accounts will be connected as we launch.</p><h3>Clear information, better decisions.</h3><p>We show listed monthly fees, explain the preferences that match, and call out details that still need confirmation.</p><p className="small-note">Apartment photography: Unsplash. Photo credits and sources are included in the project’s ASSETS.md file.</p></div></Modal>}
    {dialog==='privacy'&&<Modal title="Your privacy in this preview" close={()=>setDialog(null)}><div className="prose"><p>Without an account, your favorites, searches, and home preferences are stored in this browser. Clearing your browser data removes them. Use a private device for personal preferences.</p><p>Once sign-in is connected, account preferences and saved items are stored using Supabase and restricted to your account. If AI interpretation is enabled, submitted search text is sent to OpenAI to identify search criteria. Avoid entering sensitive personal information.</p><p>The optional map loads tiles from OpenStreetMap; that service receives standard connection information such as your IP address. We do not request your device location.</p><p>This preview does not accept rental applications, identity documents, or payments.</p><button className="secondary" onClick={()=>{setSaved([]);setSavedSearches([]);setProfile({name:'',city:'Bozeman',budget:'2200',pets:false,parking:false,laundry:false});notify('Browser preview data cleared. This does not delete account data.');}}>Clear browser preview data</button></div></Modal>}
    {dialog==='compare'&&<Modal title="A little side-by-side clarity" close={()=>setDialog(null)} wide><div className="comparison">{listings.filter(p=>compare.includes(p.id)).map(p=><article key={p.id}><img src={p.image} alt={`Illustrative interior for ${p.name}`}/><h3>{p.name}</h3><p>{p.city}, {p.state}</p><strong>{money(p.rent+p.fees)} / mo</strong><span>Including listed fees</span><hr/><p>{p.beds===0?'Studio':`${p.beds} bedroom${p.beds>1?'s':''}`} · {p.baths} baths</p><p>{p.sqft.toLocaleString()} sqft</p>{['Pet friendly','Parking','In-unit laundry','Balcony','Gym'].map(t=><p className="compare-feature" key={t}>{p.tags.includes(t)?<Check size={15}/>:<Minus size={15}/>} {t}<span className="sr-only">{p.tags.includes(t)?' included':' not listed'}</span></p>)}<button className="secondary" onClick={()=>{setDialog(null);setSelected(p);}}>View details</button></article>)}</div><p className="small-note">Sample homes. Utilities and unlisted charges are not included.</p></Modal>}
  </>;
}
createRoot(document.getElementById('root')).render(<App/>);
